<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AssemblyName>FlanderDev.SFM.MapManager</AssemblyName>
		<Product>FlanderDev's MapManager</Product>
		<Version>1.0.0</Version>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<LangVersion>latest</LangVersion>
		<RootNamespace>FlanderDev.SFM.MapManager</RootNamespace>
		<Nullable>enable</Nullable>
		<RestoreAdditionalProjectSources>
			https://api.nuget.org/v3/index.json;
			https://nuget.bepinex.dev/v3/index.json;
			https://nuget.samboy.dev/v3/index.json
		</RestoreAdditionalProjectSources>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="BepInEx.Unity.IL2CPP" Version="6.0.0-be.755" IncludeAssets="compile" />
		<PackageReference Include="BepInEx.PluginInfoProps" Version="2.1.0" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="Assembly-CSharp">
			<HintPath>..\DLLs\Assembly-CSharp.dll</HintPath>
		</Reference>
		<Reference Include="BepInEx.Core">
		  <HintPath>..\DLLs\BepInEx.Core.dll</HintPath>
		</Reference>
		<Reference Include="BepInEx.Preloader.Core">
		  <HintPath>..\DLLs\BepInEx.Preloader.Core.dll</HintPath>
		</Reference>
		<Reference Include="BepInEx.Unity.Common">
		  <HintPath>..\DLLs\BepInEx.Unity.Common.dll</HintPath>
		</Reference>
		<Reference Include="BepInEx.Unity.IL2CPP">
		  <HintPath>..\DLLs\BepInEx.Unity.IL2CPP.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppInterop.Runtime">
		  <HintPath>..\DLLs\Il2CppInterop.Runtime.dll</HintPath>
		</Reference>
		<Reference Include="Il2Cppmscorlib">
			<HintPath>..\DLLs\Il2Cppmscorlib.dll</HintPath>
		</Reference>
		<Reference Include="Unity.AI.Navigation">
		  <HintPath>..\DLLs\Unity.AI.Navigation.dll</HintPath>
		</Reference>
		<Reference Include="Unity.Animation.Rigging">
		  <HintPath>..\DLLs\Unity.Animation.Rigging.dll</HintPath>
		</Reference>
		<Reference Include="Unity.Animation.Rigging.DocCodeExamples">
		  <HintPath>..\DLLs\Unity.Animation.Rigging.DocCodeExamples.dll</HintPath>
		</Reference>
		<Reference Include="Unity.Burst">
		  <HintPath>..\DLLs\Unity.Burst.dll</HintPath>
		</Reference>
		<Reference Include="Unity.Burst.Unsafe">
		  <HintPath>..\DLLs\Unity.Burst.Unsafe.dll</HintPath>
		</Reference>
		<Reference Include="Unity.InputSystem">
			<HintPath>..\DLLs\Unity.InputSystem.dll</HintPath>
		</Reference>
		<Reference Include="Unity.InputSystem.ForUI">
		  <HintPath>..\DLLs\Unity.InputSystem.ForUI.dll</HintPath>
		</Reference>
		<Reference Include="Unity.Mathematics">
		  <HintPath>..\DLLs\Unity.Mathematics.dll</HintPath>
		</Reference>
		<Reference Include="Unity.MemoryProfiler">
		  <HintPath>..\DLLs\Unity.MemoryProfiler.dll</HintPath>
		</Reference>
		<Reference Include="Unity.Postprocessing.Runtime">
		  <HintPath>..\DLLs\Unity.Postprocessing.Runtime.dll</HintPath>
		</Reference>
		<Reference Include="Unity.RenderPipelines.Core.Runtime">
		  <HintPath>..\DLLs\Unity.RenderPipelines.Core.Runtime.dll</HintPath>
		</Reference>
		<Reference Include="Unity.Splines">
		  <HintPath>..\DLLs\Unity.Splines.dll</HintPath>
		</Reference>
		<Reference Include="Unity.TextMeshPro">
			<HintPath>..\DLLs\Unity.TextMeshPro.dll</HintPath>
		</Reference>
		<Reference Include="Unity.VisualScripting.Core">
		  <HintPath>..\DLLs\Unity.VisualScripting.Core.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine">
			<HintPath>..\DLLs\UnityEngine.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.AccessibilityModule">
		  <HintPath>..\DLLs\UnityEngine.AccessibilityModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.AIModule">
		  <HintPath>..\DLLs\UnityEngine.AIModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.AndroidJNIModule">
		  <HintPath>..\DLLs\UnityEngine.AndroidJNIModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.AnimationModule">
		  <HintPath>..\DLLs\UnityEngine.AnimationModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.AssetBundleModule">
		  <HintPath>..\DLLs\UnityEngine.AssetBundleModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.AudioModule">
		  <HintPath>..\DLLs\UnityEngine.AudioModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.ClothModule">
		  <HintPath>..\DLLs\UnityEngine.ClothModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.ClusterInputModule">
		  <HintPath>..\DLLs\UnityEngine.ClusterInputModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.ClusterRendererModule">
		  <HintPath>..\DLLs\UnityEngine.ClusterRendererModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.ContentLoadModule">
		  <HintPath>..\DLLs\UnityEngine.ContentLoadModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.CoreModule">
			<HintPath>..\DLLs\UnityEngine.CoreModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.CrashReportingModule">
		  <HintPath>..\DLLs\UnityEngine.CrashReportingModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.DirectorModule">
		  <HintPath>..\DLLs\UnityEngine.DirectorModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.DSPGraphModule">
		  <HintPath>..\DLLs\UnityEngine.DSPGraphModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.GameCenterModule">
		  <HintPath>..\DLLs\UnityEngine.GameCenterModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.GIModule">
		  <HintPath>..\DLLs\UnityEngine.GIModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.GridModule">
		  <HintPath>..\DLLs\UnityEngine.GridModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.HotReloadModule">
		  <HintPath>..\DLLs\UnityEngine.HotReloadModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.ImageConversionModule">
		  <HintPath>..\DLLs\UnityEngine.ImageConversionModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.IMGUIModule">
		  <HintPath>..\DLLs\UnityEngine.IMGUIModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.InputModule">
		  <HintPath>..\DLLs\UnityEngine.InputModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.JSONSerializeModule">
		  <HintPath>..\DLLs\UnityEngine.JSONSerializeModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.LocalizationModule">
		  <HintPath>..\DLLs\UnityEngine.LocalizationModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.ParticleSystemModule">
		  <HintPath>..\DLLs\UnityEngine.ParticleSystemModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.PerformanceReportingModule">
		  <HintPath>..\DLLs\UnityEngine.PerformanceReportingModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.Physics2DModule">
		  <HintPath>..\DLLs\UnityEngine.Physics2DModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.PhysicsModule">
			<HintPath>..\DLLs\UnityEngine.PhysicsModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.ProfilerModule">
		  <HintPath>..\DLLs\UnityEngine.ProfilerModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.PropertiesModule">
		  <HintPath>..\DLLs\UnityEngine.PropertiesModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.RuntimeInitializeOnLoadManagerInitializerModule">
		  <HintPath>..\DLLs\UnityEngine.RuntimeInitializeOnLoadManagerInitializerModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.ScreenCaptureModule">
		  <HintPath>..\DLLs\UnityEngine.ScreenCaptureModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.SharedInternalsModule">
		  <HintPath>..\DLLs\UnityEngine.SharedInternalsModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.SpriteMaskModule">
		  <HintPath>..\DLLs\UnityEngine.SpriteMaskModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.SpriteShapeModule">
		  <HintPath>..\DLLs\UnityEngine.SpriteShapeModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.StreamingModule">
		  <HintPath>..\DLLs\UnityEngine.StreamingModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.SubstanceModule">
		  <HintPath>..\DLLs\UnityEngine.SubstanceModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.SubsystemsModule">
		  <HintPath>..\DLLs\UnityEngine.SubsystemsModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.TerrainModule">
		  <HintPath>..\DLLs\UnityEngine.TerrainModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.TerrainPhysicsModule">
		  <HintPath>..\DLLs\UnityEngine.TerrainPhysicsModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.TextCoreFontEngineModule">
		  <HintPath>..\DLLs\UnityEngine.TextCoreFontEngineModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.TextCoreTextEngineModule">
		  <HintPath>..\DLLs\UnityEngine.TextCoreTextEngineModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.TextRenderingModule">
			<HintPath>..\DLLs\UnityEngine.TextRenderingModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.InputLegacyModule">
			<HintPath>..\DLLs\UnityEngine.InputLegacyModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.TilemapModule">
		  <HintPath>..\DLLs\UnityEngine.TilemapModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.TLSModule">
		  <HintPath>..\DLLs\UnityEngine.TLSModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UI">
			<HintPath>..\DLLs\UnityEngine.UI.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UIElementsModule">
		  <HintPath>..\DLLs\UnityEngine.UIElementsModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UIModule">
			<HintPath>..\DLLs\UnityEngine.UIModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UmbraModule">
		  <HintPath>..\DLLs\UnityEngine.UmbraModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UnityAnalyticsCommonModule">
		  <HintPath>..\DLLs\UnityEngine.UnityAnalyticsCommonModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UnityAnalyticsModule">
		  <HintPath>..\DLLs\UnityEngine.UnityAnalyticsModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UnityConnectModule">
		  <HintPath>..\DLLs\UnityEngine.UnityConnectModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UnityCurlModule">
		  <HintPath>..\DLLs\UnityEngine.UnityCurlModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UnityTestProtocolModule">
		  <HintPath>..\DLLs\UnityEngine.UnityTestProtocolModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UnityWebRequestAssetBundleModule">
		  <HintPath>..\DLLs\UnityEngine.UnityWebRequestAssetBundleModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UnityWebRequestAudioModule">
		  <HintPath>..\DLLs\UnityEngine.UnityWebRequestAudioModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UnityWebRequestModule">
		  <HintPath>..\DLLs\UnityEngine.UnityWebRequestModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UnityWebRequestTextureModule">
		  <HintPath>..\DLLs\UnityEngine.UnityWebRequestTextureModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UnityWebRequestWWWModule">
		  <HintPath>..\DLLs\UnityEngine.UnityWebRequestWWWModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.VehiclesModule">
		  <HintPath>..\DLLs\UnityEngine.VehiclesModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.VFXModule">
		  <HintPath>..\DLLs\UnityEngine.VFXModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.VideoModule">
		  <HintPath>..\DLLs\UnityEngine.VideoModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.VirtualTexturingModule">
		  <HintPath>..\DLLs\UnityEngine.VirtualTexturingModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.VRModule">
		  <HintPath>..\DLLs\UnityEngine.VRModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.WindModule">
		  <HintPath>..\DLLs\UnityEngine.WindModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.XRModule">
		  <HintPath>..\DLLs\UnityEngine.XRModule.dll</HintPath>
		</Reference>
	</ItemGroup>
</Project>
